### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by peterhinch** [vshymanskyy/aiodns#2]
Line 36: `int.to_bytes` requires a second arg "big" or "little".

However with that fixed, this script fails. It displays the result of the synchronous DNS query, but the async one pauses for a period then fails. Tested on a Pico W.
```py
import asyncio
import aiodns
import socket

async def main(site, port):
    print(socket.getaddrinfo(site, port))  # Works, so network is OK
    info = await aiodns.getaddrinfo(site, port)  # Pauses then throws
    print(info)

asyncio.run(main("google.com", 443))
```
Outcome:
```py
$ mpr exec "import rats"
[(2, 1, 0, '', ('172.217.169.46', 443))]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rats.py", line 11, in <module>
  File "asyncio/core.py", line 1, in run
  File "asyncio/core.py", line 1, in run_until_complete
  File "asyncio/core.py", line 1, in run_until_complete
  File "rats.py", line 7, in main
  File "aiodns.py", line 140, in getaddrinfo
OSError: Failed to resolve google.com
```
Build:
```
MicroPython v1.24.0-preview.121.g444d7bacb on 2024-07-22; Raspberry Pi Pico W with RP2040
```

**Comment by vshymanskyy** [comment]
Thanks for reporting. Weird, i definitely checked it on Pico W. Will re-check

**Comment by vshymanskyy** [comment]
Yes, it was a compatibility issue with 1.23
Fixed now

**Comment by vshymanskyy** [comment]
The example was added as well:
https://github.com/vshymanskyy/aiodns/tree/main/examples/simple
